[theme]
primaryColor = "#FF6B00"          # Naranjo corporativo
backgroundColor = "#0E1117"       # Gris oscuro analítico para el panel principal
secondaryBackgroundColor = "#FFFFFF" # Fondo blanco para la barra lateral (donde está el logo)
textColor = "#FFFFFF"             # Texto blanco por defecto para el panel principal
font = "sans serif"
